compile: mainTeste.c Jogador/TADJogador.c Jogo/TADJogo.c Localidade/TADLocalidade.c Tabuleiro/TADTabuleiro.c
	gcc -o TP1 mainTeste.c Jogador/TADJogador.c Jogo/TADJogo.c Localidade/TADLocalidade.c Tabuleiro/TADTabuleiro.c

run: 
	.\TP1.exe